---
##########################################
## Ansible Playbook for upgrading packages
##########################################

- name: update all yum packages
  yum:
    name: '*'
    state: latest
  become: true
