---
##########################################
## Ansible Playbook for upgrading packages
##########################################

- name: get dir listing
  shell: docker login -u timgondasr -p "{{ vault_dr_pass }}"
  
- debug:
    msg: "{{ vault_dr_pass }}"
