---
##########################################
## Ansible Playbook for upgrading packages
##########################################

- name: get dir listing
  shell: docker login -u timgondasr -p "{{ vault_dr_pass }}"

- debug:
    msg: "{{ vault_dr_pass }}"
    
- name: pull docker application
  shell: docker pull timgondasr/web2_web:jenkins-jenkins-docker-96

- name: Creates web directory
  file:
    path: /home/ubuntu/web
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775
  become: yes

- name: copy the compose file  
  copy:
    src: "{{workdir}}/docker-compose.yml"
    dest: /home/ubuntu/web/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: 0755
    
- name: copy the .env file
  copy:
    src: "{{workdir}}/.env"
    dest: /home/ubuntu/web/.env
    owner: ubuntu
    group: ubuntu
    mode: 0755  

- name: start web application
  shell: "{{workdir}}/docker-compose up -d"
