---
##########################################
## Ansible Playbook for upgrading packages
##########################################

- name: get dir listing
  shell: docker login -u timgondasr -p "{{ vault_dr_pass }}"

- debug:
    msg: "{{ vault_dr_pass }}"
    
- name: pull docker application
  shell: docker pull timgondasr/web2_web:jenkins-jenkins-docker-96

- name: Creates web directory
  file:
    path: /home/ubuntu/web
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755
  become: yes

- name: copy the compose file  
  copy:
    src: "{{workdir}}/docker-compose.yml"
    dest: /home/ubuntu/web/docker-compose.yml
    owner: ubuntu
    group: ubuntu
    mode: 0755
  become: yes

- name: copy the app.py file  
  copy:
    src: "{{workdir}}/app.py"
    dest: /home/ubuntu/web/app.py
    owner: ubuntu
    group: ubuntu
    mode: 0755
  become: yes

    
- name: copy the .env file
  copy:
    src: "{{workdir}}/.env"
    dest: /home/ubuntu/web/.env
    owner: ubuntu
    group: ubuntu
    mode: 0755
  become: yes  

- name: start web application
  command:  "docker-compose up -d"
  args: 
    chdir: /home/ubuntu/web
    
- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: 'http://127.0.0.1:5000'

# Check that a page returns a status 200 and fail if the word AWESOME is not
# in the page contents.
- name: is webserver started
  uri:
    url: 'http://127.0.0.1:5000'
    return_content: yes
  register: webpage

- name: Fail if carbon is not in the page content
  fail:
  when: "'carbon' not in webpage.content"


    
