---
# tasks file for web

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:

  - name: print out the hostname of target
    command: hostname
  
  - name: update the apt package index i.e. apt-get update
    apt: update_cache=yes
